name: baato_maps
description: "A Flutter package for Baato Maps. Baato Maps is a powerful and flexible mapping solution for Flutter applications."
version: 1.0.1
homepage: https://github.com/baato/flutter_baato_maps
license: MIT

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.19.0+2
  # baato_api: ^2.0.1
  baato_api:
      git: 
        url: https://github.com/baato/baato-flutter.git
        ref: lower_sdk_support
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - lib/assets/markers/
    - lib/assets/map_res/sprites/
    - lib/assets/logo/
